# syntax=docker/dockerfile:1.7

########################################
# Base image versions
ARG NODE_VERSION=20

########################################
# 1) Builder: install deps and build
FROM node:${NODE_VERSION}-slim AS deps

WORKDIR /app

# Install OS deps needed for optional packages (canvas/sharp etc.) if present
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates git openssl \
    && rm -rf /var/lib/apt/lists/*

# Copy lockfile and package.json for better caching
COPY package.json package-lock.json* ./

# Install npm dependencies (respect lockfile, allow peer dep conflicts)
RUN npm ci --no-audit --no-fund --legacy-peer-deps

########################################
# 2) Builder: compile Next.js app
FROM node:${NODE_VERSION}-slim AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the app (outputs .next/standalone when output: "standalone")
RUN npm run build

########################################
# 3) Runtime: minimal image using standalone output
FROM node:${NODE_VERSION}-slim AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Create non-root user for security
RUN groupadd -r nextjs && useradd -r -g nextjs nextjs \
  && mkdir -p /app/.next \
  && chown -R nextjs:nextjs /app

# Copy standalone server and static assets
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

USER nextjs

EXPOSE 3000

# Start the server generated by Next.js (standalone)
CMD ["node", "server.js"]
